### ISSUE TITLE
[Lorie][Suzu] Ошибка в приложении Bluetooth

### ISSUE THREAD

**Issue by nikita-ximik** [ExplosiveLobster/bug_tracker#1]
**Device:Sony Xperia X**
**Kernel version:4.9**
**Android version:10**

**Describe the bug:**
При включении телефона появляется такая ошибка
![Screenshot_20200115-083427](https://user-images.githubusercontent.com/37953446/72740920-77f0f700-3bc8-11ea-9262-10f0937a25a6.png).
Появляется она каждые 2-3 секунды, из-за чего невозможно пользоваться прошивкой. После удаления ошибка пропала.

**To Reproduce:**

**System/Kernel logs:**

**Additional context:**

**Comment by bartcubbins** [comment]
fixed on next Android 11 release
