### ISSUE TITLE
[Suzu] [R] can't access Microphone 

### ISSUE THREAD

**Issue by TechnoHT** [ExplosiveLobster/bug_tracker#11]
AOSP R

Some apps ( Discord ) can't use Microphone while in call, not happen with some apps like Google Recorder

Log : https://drive.google.com/file/d/12BoOgSsNulnSe_mUABxQ9hNz2Rb-hVsR/view?usp=drivesdk

**Comment by bartcubbins** [comment]
confirmed. this is VoWiFi issue. not only Discord affected

**Comment by bartcubbins** [comment]
Fixed in: https://github.com/ExplosiveLobster/device_sony_common/commit/ab3d6fd4597db04b37371bf93ed052a5298de20e
Tested with Discord, Skype.
