### ISSUE TITLE
[R]Wifi doesn't work on F5122

### ISSUE THREAD

**Issue by vonmatterlorenzohorn** [ExplosiveLobster/bug_tracker#12]
Device:*F5122*
Kernel version:*4.9*
Android version:*11*

**Describe the bug:**
Turning the WiFi on does nothing. adb logcat tells me it's some kind of vendor issue. Tried even after restoring once to stock ROM and following all the steps.

**Comment by bartcubbins** [comment]
Attach logs. Without logs I can't do anything

**Comment by vonmatterlorenzohorn** [comment]
[logcat.txt](https://github.com/ExplosiveLobster/bug_tracker/files/5760168/logcat.txt)
Sorry, here's the logs. The issue I was talking about is at location 01-01 07:18:47.889, and the log was taken from boot. As you can see later in the log, bluetooth turns on just fine..

**Comment by bartcubbins** [comment]
Please attach kernel logs as well. Thank you:)

**Comment by vonmatterlorenzohorn** [comment]
Okay, how do I take kernel logs?

**Comment by bartcubbins** [comment]
adb shell dmesg after trying to turn on the wifi

**Comment by lubik1** [comment]
> Okay, how do I take kernel logs?

please provide to us kernel log or we must close this thread.
[How to ](https://www.xda-developers.com/how-to-take-logs-in-android/)

**Comment by vonmatterlorenzohorn** [comment]
Sorry guys, have been a bit busy.. Here you go.
[dmesg.log](https://github.com/ExplosiveLobster/bug_tracker/files/5780157/dmesg.log)

**Comment by lubik1** [comment]
have catched a bug with wi-fi too
logs:
[dmesg.log](https://github.com/ExplosiveLobster/bug_tracker/files/5789772/dmesg.log)
[bug wi-fi.txt](https://github.com/ExplosiveLobster/bug_tracker/files/5789775/bug.wi-fi.txt)

**Comment by Seegras** [comment]
Same here. But I'm on F5121, not F5122.

[logcat.log](https://github.com/ExplosiveLobster/bug_tracker/files/5899633/logcat.log)
[dmesg.log](https://github.com/ExplosiveLobster/bug_tracker/files/5899634/dmesg.log)

**Comment by vonmatterlorenzohorn** [comment]
> Same here. But I'm on F5121, not F5122.


You can flash the stock ROM and then without booting into it, flash EL as per the instructions over at XDA. It's a temporary fix but it works.

**Comment by bartcubbins** [comment]
Most likely I found a solution, I will test everything with @lubik1 and let you know as soon as possible.
Thanks for the logs!

**Comment by Seegras** [comment]
Hang on, you flash the stock rom not into the eom partition, but into the working one? And if yes, which ROM? SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_loire.zip ?

**Comment by bartcubbins** [comment]
I fixed this WiFi issue.
Also, you no longer need to flash any OEM (SW binaries) images. Please wait for the next ROM update, which will release very soon;)
Thanks!

**Comment by vonmatterlorenzohorn** [comment]
Issue fixed, closing.
