### ISSUE TITLE
[loire][suzu] NFC don't work

### ISSUE THREAD

**Issue by Krokosaber** [ExplosiveLobster/bug_tracker#13]
Device:xperia x 1 sim
Kernel version:4.9
Android version:11

NFC don't turn on. Don't working gpay and other services for payment..

**Comment by bartcubbins** [comment]
Can't confirm this. I think @lubik1 as well.
Payment stuff issues are not related to NFC, they don't work because the device is rooted.

**Comment by lubik1** [comment]
> Can't confirm this. I think @lubik1 as well.
> Payment stuff issues are not related to NFC, they don't work because the device is rooted.

Yep! NFC worked fine, just tested on my Headphones and nfc tags

**Comment by lubik1** [comment]
Cant confirm that we have any problems with NFC. Gpay worked fine with cts configs from stock fw (magisk module) and magisk hide
