### ISSUE TITLE
MicroG support

### ISSUE THREAD

**Issue by mase76** [ExplosiveLobster/bug_tracker#14]
Hi! Can you apply the patches for MicroG, for all the people, who don't want to install the Playservices?
These can be found here:
https://github.com/microg/UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch

https://github.com/microg/GmsCore/wiki/Signature-Spoofing

**Comment by lubik1** [comment]
Spoofing signature added on new build 07.01.2021

**Comment by bartcubbins** [comment]
This is for the record. Implemented in:
https://github.com/ExplosiveLobster/platform_frameworks_base/commit/72ff236cdf8a203b7852c2e4a9705c0564097b67
https://github.com/ExplosiveLobster/platform_packages_apps_PermissionController/commit/8d1543d3ad5da8b4869dbda30f1e06548ef484ac
