### ISSUE TITLE
[Lorie][Suzu] Внутренняя ошибка

### ISSUE THREAD

**Issue by nikita-ximik** [ExplosiveLobster/bug_tracker#2]
**Device:Sony Xperia X**
**Kernel version:4.9**
**Android version:10**

**Describe the bug**
Каждый раз при включении появляется такая ошибка:
![Screenshot_20200115-083412](https://user-images.githubusercontent.com/37953446/72742748-31050080-3bcc-11ea-8145-5a69b47540cc.png)

**Comment by bartcubbins** [comment]
caused by mismatched system and vendor fingerprints.
appears when you make a "dirty" build. not an actual error.
