### ISSUE TITLE
[Suzu] Bug report

### ISSUE THREAD

**Issue by sjllls** [ExplosiveLobster/bug_tracker#5]
Hi,
    After tested, I found two issues,:
    1.  Kernel branch `LA.UM.8.8.r1-07500-SDM710.0` seems to be bootloop after testing on both Android 10 and 11.
    2. Kernel branch `LA.UM.8.8.r1-06100-SDM710.0` could boot on Android 10, but bluetooth seems be broken. It can't find mac address.
    And for android 10 branch,  `kernelscripts` also needs to enable clang, using GCC will report an error about openssl.
    Bluetooth log:
    
[1.txt](https://github.com/ExplosiveLobster/bug_tracker/files/5433973/1.txt)

```
10-24 23:32:44.111  3356  4023 D BluetoothAdapter: onBluetoothServiceDown: android.bluetooth.IBluetooth$Stub$Proxy@44d1d06
10-24 23:32:44.111  6919  6919 F DEBUG   : uid: 1002
10-24 23:32:44.112  6919  6919 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
10-24 23:32:44.112  6919  6919 F DEBUG   : Abort message: 'Open: No Bluetooth Address!'
```

**Comment by bartcubbins** [comment]
this is a known problem with the 7500 tag, we will switch to 9.8 kernel branch asap.

**Comment by bartcubbins** [comment]
Bluetooth is fixed now. Tested on Android 11.
About Android 10, I think there is no point in maintaining it when we have Android 11 with completely the same working functionality. What do you think?

**Comment by sjllls** [comment]
> Bluetooth is fixed now. Tested on Android 11.
> About Android 10, I think there is no point in maintaining it when we have Android 11 with completely the same working functionality. What do you think?

Nice work! I already fixed bluetooth on android 10 in a simple way. :P
https://github.com/sjllls/device-sony-loire/commit/84f9115a815d69cd9079cbb77e95c5536f4fe85b
