### ISSUE TITLE
[Suzu] Treble issue

### ISSUE THREAD

**Issue by TechnoHT** [ExplosiveLobster/bug_tracker#6]
Xperia X Dual ( suzu )
Kernel : 4.9
HavocOS 3.8, LineageOS 17.1

No audio when playing a .mp3 file, .flac and .wav give normal sound ( Temporary Fix : install V4A aka Viper and set to Legacy Mode )
Device freeze a bit when waking up from deep sleep, but seem not affecting normal usage
 
Update 4/11/2020 : Fingerprint not working ( HavocOS 3.8 )

Update 6/11/2020 : Device reboot when handling some task while deep sleep ( D : Downloading a large app or files )

Update 13/11/2020 : Random freeze ( or looping, flickering ) state 

Update 17/11/2020 : Apps can't access/use camera such as Open Camera ( can't save photo with back camera, might be GSI bug ), Front camera are completely unavailable on some apps.

**Comment by sjllls** [comment]
Confirmed mp3 crashing.
Here is log.
[mp3.txt](https://github.com/ExplosiveLobster/bug_tracker/files/5479729/mp3.txt)

**Comment by TechnoHT** [comment]
( not fully tested ) .mp3 is playable by using Viper ( Legacy mode ) not sure why ( HavocOS 3.8 )

**Comment by TechnoHT** [comment]
Prompted the "Failed Verification Warning" during deep sleep ( found out while sleeping lol )

**Comment by bartcubbins** [comment]
Temporary audio fix: https://github.com/ExplosiveLobster/device_sony_loire/commit/ff905c9467451d2c5ee7c03d93a011eadcaf371f

**Comment by TechnoHT** [comment]
![Screenshot_20201228-233004.jpg](https://user-images.githubusercontent.com/56500340/103228988-72259900-4975-11eb-8eca-f0d71ae858f6.jpg)

front camera completely broken ( duplicate image ) in some apps, like internal Face Unlock, Microsoft Teams or Messenger ( old version ), some apps show normal image like stock camera, Open Camera, Discord

**Comment by TechnoHT** [comment]
most of the things are fixed so i will close it ( and Treble Q don't have any further update though )
