### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by temyich** [ExplosiveLobster/bug_tracker#7]
**Xperia X Dual ( suzu )**
**Kernel : 4.9**
**Android 11**
При вызове не слышно собеседника(ни с динамика, ни по громкой связи) и собеседник не слышит меня. 
В плеере не слышна музыка ни в наушниках, ни с динамика. часто плеер крашится. мелодия при вызове проигрывается.
twrp слетает после каждой перезагрузки.

**Comment by bartcubbins** [comment]
Fixed in: https://github.com/ExplosiveLobster/device_sony_loire/commit/ff905c9467451d2c5ee7c03d93a011eadcaf371f
twrp overwriting will be fixed soon
