### ISSUE TITLE
[Suzu] Can't make calls.

### ISSUE THREAD

**Issue by PitfallYKMR** [ExplosiveLobster/bug_tracker#8]
**Device: Suzu F5122**
**Kernel version: 4.9**
**Android version: 11**

**Describe the bug:**
I can't hear a companion and companion can't hear me. Microphone and speakers work correctly if you try Google search...

**To Reproduce:**
1. Try to make or receive a call.
Error appears: You can't hear a companion and companion can't hear you.

**Comment by bartcubbins** [comment]
Fixed in: https://github.com/ExplosiveLobster/device_sony_loire/commit/ff905c9467451d2c5ee7c03d93a011eadcaf371f
