### ISSUE TITLE
[Loire][Suzu] GPS навигация

### ISSUE THREAD

**Issue by temyich** [ExplosiveLobster/bug_tracker#9]
**Device:Suzu F5122**
**Kernel version:4.9**
**Android version:11**

**Describe the bug:**
Не работает GPS навигация в приложении Карты. Ни по LTE, ни по WIFI.

**Comment by temyich** [comment]
Если смарт на зарядке и выключить, то он перезагрузится.
И если из рекавери сбросить **кэш**, то система больше не запустится. 
Переустановку достаточно сделать так:
1) сбросить кэш, делвик, дата.
2) установить прошивку и SW_binaries...

Можете добавить калькулятор и хром в прошивку?

**Comment by bartcubbins** [comment]
> И если из рекавери сбросить **кэш**, то система больше не запустится.

Потому что раздел /cache мы используем как /vendor
https://github.com/ExplosiveLobster/device_sony_loire/commit/dac18fd6cc0643dc8b267132af49e1d70c200285

**Comment by bartcubbins** [comment]
Калькулятор добавлю. Про хром не уверен, возможно хромиум.

**Comment by temyich** [comment]
Ещё 2 момента:
1-в папке PRODUCT/APP есть приложение music.app, но плеера в системе не обнаружил.
2-в приложении ОБОИ нету самих обоев(пусто), хотя в системе загружены. И некоторые выглядят так.
[SPOILER]![Screenshot_20201228-231409](https://user-images.githubusercontent.com/76551140/103271447-19d5b200-49dc-11eb-96a2-18bbb8b1fdd6.png)
![Screenshot_20201228-231422](https://user-images.githubusercontent.com/76551140/103271454-1e01cf80-49dc-11eb-8f3b-45615f09c52c.png)
![Screenshot_20201228-231513](https://user-images.githubusercontent.com/76551140/103271458-21955680-49dc-11eb-9da1-7bf339aba23b.png)
![Screenshot_20201228-231526](https://user-images.githubusercontent.com/76551140/103271462-24904700-49dc-11eb-8738-2aaafce93cf6.png)
![Screenshot_20201228-231536](https://user-images.githubusercontent.com/76551140/103271467-26f2a100-49dc-11eb-88bb-e57a239f0301.png)
![Screenshot_20201228-231544](https://user-images.githubusercontent.com/76551140/103271472-2954fb00-49dc-11eb-9395-a6384193b81d.png)
![Screenshot_20201228-231716](https://user-images.githubusercontent.com/76551140/103271477-2e19af00-49dc-11eb-94b1-f83e41e993cd.png)[/SPOILER]

**Comment by bartcubbins** [comment]
для каждого бага отдельный кейс пожалуйста. потому что возникает путаница

**Comment by bartcubbins** [comment]
Improved in the next build.
![Screenshot_20210103-121057](https://user-images.githubusercontent.com/6766319/103490062-e81c7b00-4e21-11eb-9fa4-69a80a29babe.png)
![Screenshot_20210103-121103](https://user-images.githubusercontent.com/6766319/103490065-ee125c00-4e21-11eb-9313-7c9dd5c0e38f.png)
